### ISSUE TITLE
Firstnames with special characters will not be generated correctly

### ISSUE THREAD

**Issue by kbayraktar** [Inbot/inbot-testfixtures#12]
There are special characters in file 	firstname_extended.csv like 'Çığıl' for example.

After generating an email address only the standard ANSII characters are presented 
so we will get something like "l.mysurename.@mycompany.com" instead of "çığıl.mysurename@mycompany.com
Same behaviour with domain names form companies with special characters

**Comment by jillesvangurp** [comment]
This is intentional, special character in email addresses are not that well supported and would break stuff with validation regular expressions for us. First/last names should be as listed in the csv.

https://github.com/Inbot/inbot-testfixtures/blob/master/src/main/java/io/inbot/testfixtures/Person.java#L39

Not the nicest code but can't really change that currently as that would likely break a lot of tests for us.
