### ISSUE TITLE
Collections.synchronizedList should not be used

### ISSUE THREAD

**Issue by witoldsz** [Inbot/inbot-testfixtures#3]
All the lists are wrapped with `Collections.synchronizedList`. What's the reason? That makes the lists really slow, and they are read only.

**Comment by jillesvangurp** [comment]
I agree it looks a bit ugly. We run our tests concurrently, so we needed some concurrency control. We actually ran into a race condition with this at some point; I don't recall the exact circumstances though. This fixed it. For memory size and lookup speed, I prefer to use an ArrayList here, which we can only make thread safe via Colllections.synchronizedList. Otherwise I could have gone for ConcurrentLinkedList. In any case, the synchronization should mostly be optimized away by the jvm, so I'd be surprised if it actually is a bottleneck. But if you have evidence that there is a bottleneck here, feel free to create a pull requests for this. I'd prefer to keep the lookups O(1) though.
